### ISSUE TITLE
Chef encountered an error attempting to load the node data for "fauxhai.local"

### ISSUE THREAD

**Issue by chef1729** [chefspec/fauxhai#274]
================================================================================
Chef encountered an error attempting to load the node data for "fauxhai.local"
================================================================================

Authentication Error:
---------------------
Failed to authenticate to the chef server (http 401).

Server Response:
----------------

Relevant Config Settings:
-------------------------
chef_server_url   "https://radche/organizations/radian"
node_name         "fauxhai.local"
client_key        ""

If these settings are correct, your client_key may be invalid, or
you may have a chef user with the same client name as this node.

Platform:
---------
x86_64-linux

    example at ./spec/recipes/default_spec.rb:25 (FAILED - 6)

**Comment by coderanger** [comment]
You are probably trying to access some Chef Server features from ChefSpec's SoloRunner. This is not supported.
