### ISSUE TITLE
Migrate to chefspec org

### ISSUE THREAD

**Issue by sethvargo** [chefspec/fauxhai#288]
Hi there!

We recently moved ChefSpec to its own organization. As you know, fauxhai is a crucial part of ChefSpec's operation, and I vote to move it into the new chefspec org. 

Since this is officially a CustomInk project that I worked on as an intern at CustomInk, I'm not sure the licensing/process for approval.

/cc @clumpidy @nathenharvey @tas50

**Comment by clumpidy** [comment]
I'll check.

**Comment by clumpidy** [comment]
Hey Seth,

  You're welcome to move the project. Our legal team has no problems with that.

Thanks,
Jake.

**Comment by sethvargo** [comment]
Hey @clumpidy 

Wow sweet! Thank you for taking the time to check on that. I don't have admin permissions on the project. Can you promote me to "Admin" so I can move it over please?

**Comment by clumpidy** [comment]
done

**Comment by sethvargo** [comment]
Done! Thanks a bunch!
