### ISSUE TITLE
The OpenSUSE 15.0 platform_family is `null` (fauxhai ingestion needs validation)

### ISSUE THREAD

**Issue by lamont-granquist** [chefspec/fauxhai#344]
That platform is deprecated (so this specific issue will go away) but the fact that there's fauxhai data which has a platform_family of null is a larger bug around having some better validation that certain keys must be present and not null

**Comment by tas50** [comment]
I just reran the dump command and that's updated the data from Chef 14 to 16 which includes 2x the data in the dump.
