### ISSUE TITLE
Deprecation warning on Ruby 2.7

### ISSUE THREAD

**Issue by tas50** [chefspec/fauxhai#349]
/usr/local/lib/ruby/gems/2.7.0/gems/fauxhai-ng-8.2.0/lib/fauxhai/mocker.rb:50: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open

**Comment by mattray** [comment]
Same issue here: https://github.com/chef/omnibus/pull/940

**Comment by tas50** [comment]
Fixed
